theme: jekyll-theme-minimal
title: John Kenneth Fajardo's CV
description:
  I am anyone you want me to be...and also an aspiring data scientist
  :email: johnkennethfajardo@gmail.com / :iphone:  0917 489 3584

