theme: jekyll-theme-minimal
title: John Kenneth Fajardo
description: >
  I am a developer who has relevant experience in the field of research - whether it be writing scientific articles, programming, or even leading. Whatever it is, I do to serve, and I follow through. I am also hoping into transitioning to a more data-focused career.   
  📧 johnkennethfajardo@gmail.com
  📱  0917 489 3584

