theme: jekyll-theme-minimal
title: John Kenneth Fajardo
description: >
  I am a developer who has relevant experience in the field of research - whether it be writing scientific articles, programming, or even leading, as long as it is needed for the job. I am also hoping into transitioning to a more data-related career.   
  📧 johnkennethfajardo@gmail.com
  📱  0917 489 3584

