theme: jekyll-theme-minimal
title: John Kenneth Fajardo's CV
description: 
  I am anyone you want me to be ... and also an aspiring data scientist \n
  📧 johnkennethfajardo@gmail.com \n
  📱  0917 489 3584\n

